"""
Multi-ARCHITECTURE CNN ECC energy sweep -- BCH(63,51), 3-way, all 8 models.

Companion to run_ecc_multimodel_n7.py. Two differences:

  * GEOMETRY. All three arms share ONE BCH(63,51) codeword (t=2, d_min=5,
    r=12), instead of the N=7 script's per-arm Hamming(11,7)/(7,6)/(7,6).
    This is the model of E3-CODE/Run_ecc_multimodel_3way.py.

  * SCOPE. Sweeps FIVE architectures, not two, so Eyeriss v2 can be compared
    against Eyeriss v1 and the three reference designs.

The three arms, all on BCH(63,51) with 8-bit weights:

  1. Baseline   -- parity stored alongside the data; DRAM weight traffic
                   inflates by N/K = 63/51 (+23.5%).
  2. Embedded   -- parity embedded in the already-stored word; no DRAM
                   inflation.
  3. Recon+     -- same codeword; DRAM as embedded; only K/N = 51/63 of the
                   WEIGHT data is held on-chip; the parity portion is
                   regenerated by the synthesized reconstruction datapath,
                   charged per codeword from Design Compiler.

Weights per codeword = K/8 = 6.375 for every arm, so the arms differ only in
where the parity lives -- which is the point of the comparison.

ECC decode is charged as ZERO for all three arms (INCLUDE_ECC_DECODE = False);
the category sums to zero and is dropped from the bars and the legend.

------------------------------------------------------------------------------
PROVENANCE
------------------------------------------------------------------------------
* Reconstruction energy is read at runtime from BCH_N63_results.json (copied
  next to this script from dc_energy_starter/results/), entry BCH_63_51_t2:
  incremental 1.8995 + idle 2.2301273 = 4.1296273 pJ/codeword.
  FreePDK45/OSU gscl45nm, 1.1 V, 1 ns clock, pre-layout with a wire-load model.
  Unlike the N=7 script there is NO geometry mismatch here: the synthesized
  circuit and the modelled codeword are both BCH(63,51).

* All five architectures are now declared at 45nm, so Accelergy costs them at
  the same process node and an energy gap reflects architecture, not silicon.
  DRAM sits above the accelerator container and takes the technology from
  ecc_energy_study/globals.yaml, identically for every architecture.

------------------------------------------------------------------------------
RUNTIME WARNING -- READ BEFORE STARTING
------------------------------------------------------------------------------
The mapper cache is per-architecture. At the time of writing:

    simple_weight_stationary   221/221 cached  -> seconds
    eyeriss_like                 0/221 cached  -> full re-map (was cached at
                                                  65nm; archived when the
                                                  architecture moved to 45nm)
    eyeriss_v2_like              0/221 cached  -> full map, new architecture
    simba_like                  12/221 cached  -> ~209 to map
    simple_output_stationary    12/221 cached  -> ~209 to map

That is roughly 860 fresh mappings. Budget HOURS and leave it running. The run
is resumable: every solved shape is cached, so restarting picks up where it
stopped. Raw per-architecture energies are also written to
multiarch_bch63_k51_raw.json as each architecture finishes, so the figures can
be regenerated later without touching the mapper (REPLOT_ONLY = True).

RUN INSIDE the container, launched from Energy_modeling/ :
    cd /home/workspace
    python3 E3-CODE/Proposal/run_ecc_multiarch_bch63.py

Outputs land NEXT TO THIS FILE (E3-CODE/Proposal/).
"""
import os, re, glob, json, math, pathlib, shutil, contextlib
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib as mpl

try:
    import pytimeloop.timeloopfe.v4 as tl
except ImportError:
    import timeloopfe.v4 as tl

# ================= DECISION: split on-chip storage into read/write? ===========
SeperateBreakdown = False     # True  -> GB & Local each split read+write
                              # False -> single bar per on-chip level
# =============================================================================

# ============================ USER KNOBS =====================================
ARCHS = [
    "eyeriss_v2_like",            # the new model -- run it first so it lands early
    "eyeriss_like",
    "simple_weight_stationary",
    "simba_like",
    "simple_output_stationary",
]

REPLOT_ONLY = False   # True -> skip the mapper entirely and rebuild the figures
                      # from multiarch_bch63_k51_raw.json

MODELS_TO_RUN = [
    "resnet18",
    # "resnet50",
    # "densenet121",
    # "squeezenet1_1",
    # "mobilenet_v2",
    # "efficientnet_b0",
    # "convnext_tiny",
    # "xception",
]

WEIGHT_BITS = 8               # 8-bit quantization
VICTORY     = 500             # mapper effort (only used if a shape is uncached)

# ---- codeword geometry: ONE code shared by all three arms --------------------
BCH_N = 63                    # codeword length
BCH_K = 51                    # message length  (t=2, d_min=5, r=12)

# ---- controller decode energy ----------------------------------------------
# INCLUDE_ECC_DECODE = False -> decode charged as ZERO for all three arms; the
# category sums to 0 everywhere so plot_arch()'s `active` filter drops it from
# the stacks AND the legend. Set True to restore it.
INCLUDE_ECC_DECODE = False

# Only used when INCLUDE_ECC_DECODE is True. ESTIMATES, not measurements.
E_DECODE_BASE_PJ = 40.0       # pJ/codeword, BCH(63,51) syndrome+Chien decode
E_DECODE_EMB_PJ  = 40.0       # same code, so same decoder
RECON_CHARGES_DECODE = True   # does Recon+ still pay detection before rebuilding?

# Does the baseline's parity also inflate ON-CHIP traffic, or only DRAM?
# The parent E3-CODE scripts inflate DRAM only; kept False for continuity.
BASELINE_INFLATES_ONCHIP = False

# ---- palette ----------------------------------------------------------------
# False -> the house palette used by the other E3-CODE figures.
# True  -> an Okabe-Ito palette that passes a colourblind-safety validator.
#          The house palette's "Global buffer" green and "On-chip SRAM/RF" amber
#          are adjacent segments in the stack and sit at dE 7.9 under protanopia,
#          which is the marginal band; the amber is also under 3:1 contrast on
#          white. Flip this to True for print / accessibility-sensitive venues.
CVD_SAFE_PALETTE = False

# ---- reconstruction energy, from the Design Compiler run ---------------------
RECON_JSON         = "BCH_N63_results.json"      # sits next to this script
RECON_CONFIG_ID    = "BCH_63_51_t2"
RECON_INCLUDE_IDLE = True     # True -> incremental + idle (4.1296273 pJ/cw)
                              # False -> incremental only  (1.8995 pJ/cw)
RECON_INCREMENTAL_FALLBACK_PJ = 1.8995
RECON_IDLE_FALLBACK_PJ        = 2.2301273
# =============================================================================


# ---------------- setup: repo + design paths ---------------------------------
assert shutil.which("timeloop-mapper"), "timeloop-mapper not on PATH -- run inside the container"

WORK = pathlib.Path.cwd() / "ecc_energy_study"
WORK.mkdir(exist_ok=True)
try:
    FIG_DIR = pathlib.Path(__file__).resolve().parent      # E3-CODE/Proposal/
except NameError:
    FIG_DIR = WORK
FIG_DIR.mkdir(parents=True, exist_ok=True)

EX_REPO = WORK / "timeloop-accelergy-exercises"
assert EX_REPO.exists(), ("exercises repo missing -- run E3-CODE/run_ecc_study.py once "
                          "first to clone it, and launch from /home/workspace")
DESIGNS_DIR = EX_REPO / "workspace" / "example_designs" / "example_designs"

# ---- install locally-authored architectures into the (re-clonable) repo ------
# Master copies live next to this script so they survive a wipe of
# ecc_energy_study/. Copied in whenever they are missing or newer.
def install_local_archs():
    import shutil as _sh
    for master in sorted(FIG_DIR.glob("*_like")):
        if not master.is_dir():
            continue
        dst = DESIGNS_DIR / master.name
        dst.mkdir(parents=True, exist_ok=True)
        for f in master.iterdir():
            if not f.is_file():
                continue
            t = dst / f.name
            if (not t.exists()) or f.stat().st_mtime > t.stat().st_mtime:
                _sh.copy2(f, t)
                print(f"  [install] {master.name}/{f.name} -> example_designs/")

install_local_archs()
assert (WORK / "model_layers.json").exists(), \
    "model_layers.json missing -- run E3-CODE/generate_models.py first"
model_layers = json.loads((WORK / "model_layers.json").read_text())

(WORK / "globals.yaml").write_text(
    'variables:\n  version: 0.4\n  global_cycle_seconds: 1e-9\n  technology: "65nm"\n')


# ---------------- reconstruction energy ---------------------------------------
def load_recon_energy():
    """Return (E_recon_per_codeword_pJ, provenance_string)."""
    path = FIG_DIR / RECON_JSON
    if path.exists():
        try:
            entries = json.loads(path.read_text())
            if isinstance(entries, dict):
                entries = [entries]
            for e in entries:
                if e.get("configuration_id") == RECON_CONFIG_ID:
                    inc  = float(e["energy_pJ"]["incremental_per_codeword"])
                    idle = float(e["energy_pJ"]["idle_per_cycle"])
                    val  = inc + idle if RECON_INCLUDE_IDLE else inc
                    how  = "incremental+idle" if RECON_INCLUDE_IDLE else "incremental only"
                    return val, (f"{path.name} [{RECON_CONFIG_ID}] "
                                 f"n={e.get('n')} k={e.get('k')} t={e.get('t')} ({how}): "
                                 f"inc={inc:.7f} idle={idle:.7f}")
            print(f"[warn] {RECON_CONFIG_ID} not found in {path.name}; using fallback")
        except Exception as exc:
            print(f"[warn] could not parse {path.name}: {exc}; using fallback")
    else:
        print(f"[warn] {path.name} not found next to this script; using fallback")
    val = (RECON_INCREMENTAL_FALLBACK_PJ +
           (RECON_IDLE_FALLBACK_PJ if RECON_INCLUDE_IDLE else 0.0))
    return val, "hardcoded fallback constants"

E_RECON_CW_PJ, RECON_PROVENANCE = load_recon_energy()


# ---------------- per-architecture timeloop plumbing --------------------------
PROBLEM_TEMPLATE = """problem:
  version: 0.4
  shape:
    name: cnn_layer
    coefficients:
      - name: Wstride
        default: 1
      - name: Hstride
        default: 1
      - name: Wdilation
        default: 1
      - name: Hdilation
        default: 1
    dimensions: [ C, M, R, S, N, P, Q ]
    data_spaces:
      - name: Weights
        projection:
          - [ [C] ]
          - [ [M] ]
          - [ [R] ]
          - [ [S] ]
      - name: Inputs
        projection:
          - [ [N] ]
          - [ [C] ]
          - [ [R, Wdilation], [P, Wstride] ]
          - [ [S, Hdilation], [Q, Hstride] ]
      - name: Outputs
        projection:
          - [ [N] ]
          - [ [M] ]
          - [ [Q] ]
          - [ [P] ]
        read_write: True
  instance:
    C: {C}
    M: {M}
    R: {R}
    S: {S}
    N: {N}
    P: {P}
    Q: {Q}
    Wstride: {Wstride}
    Hstride: {Hstride}
"""
PROB_DIR = WORK / "problems_multimodel"
PROB_DIR.mkdir(exist_ok=True)


def patched_arch_path(arch):
    """Same DRAM-depth patch the parent scripts apply, per architecture."""
    src = DESIGNS_DIR / arch / "arch.yaml"
    dst = WORK / f"arch_{arch}_patched.yaml"
    text = src.read_text()
    dram_attrs = text.split("name: DRAM")[1].split("!")[0] if "name: DRAM" in text else ""
    if "depth" not in dram_attrs:
        text = text.replace(
            'class: DRAM\n    attributes:\n      type: "LPDDR4"',
            'class: DRAM\n    attributes:\n      depth: 1048576\n      type: "LPDDR4"')
    dst.write_text(text)
    return dst


def make_problem(sig):
    C, M, R, S, P, Q, Ws, Hs = sig
    name = f"C{C}_M{M}_R{R}_S{S}_P{P}_Q{Q}_ws{Ws}_hs{Hs}"
    path = PROB_DIR / f"{name}.yaml"
    if not path.exists():
        path.write_text(PROBLEM_TEMPLATE.format(C=C, M=M, R=R, S=S, N=1, P=P, Q=Q,
                                                Wstride=Ws, Hstride=Hs))
    return name, path


def design_inputs(arch_yaml, problem_yaml):
    files = [str(arch_yaml)]
    files += sorted(glob.glob(str(DESIGNS_DIR / "_components" / "*.yaml")))
    files.append(str(DESIGNS_DIR / "_include" / "mapper.yaml"))
    files.append(str(WORK / "globals.yaml"))
    files.append(str(problem_yaml))
    return files


_sig_cache = {}          # (arch, sig) -> stats path or None


def run_shape(arch, arch_yaml, out_root, sig):
    key = (arch, sig)
    if key in _sig_cache:
        return _sig_cache[key]
    name, prob = make_problem(sig)
    out_dir = out_root / name
    stats = out_dir / "timeloop-mapper.stats.txt"
    if stats.exists():                       # cache hit -- the common path
        _sig_cache[key] = stats
        return stats
    print(f"      mapping {name} ...", flush=True)   # uncached: this is the slow path
    spec = tl.Specification.from_yaml_files(*design_inputs(arch_yaml, prob))
    spec.mapper.num_threads = os.cpu_count() or 4
    spec.mapper.victory_condition = VICTORY
    spec.mapper.timeout = 10000
    spec.mapper.algorithm = "hybrid"
    out_dir.mkdir(parents=True, exist_ok=True)
    try:
        with open(out_dir / "mapper_console.log", "w") as _logf, \
             contextlib.redirect_stdout(_logf), contextlib.redirect_stderr(_logf):
            tl.call_mapper(spec, output_dir=str(out_dir))
    except Exception:
        _sig_cache[key] = None
        return None
    _sig_cache[key] = stats if stats.exists() else None
    return _sig_cache[key]


def _grab(pat, text):
    m = re.search(pat, text)
    return float(m.group(1)) if m else None


def parse_stats(stats_path, layer):
    text = pathlib.Path(stats_path).read_text()
    rows, chunks = [], re.split(r"===\s*(.+?)\s*===", text)[1:]
    for level, body in zip(chunks[0::2], chunks[1::2]):
        parts = re.split(r"\n\s+(Weights|Inputs|Outputs)\s*:\s*\n", body)
        if len(parts) > 1:
            for ds, sec in zip(parts[1::2], parts[2::2]):
                reads   = _grab(r"Scalar reads \(per-instance\)\s*:\s*([\d.eE+]+)", sec)
                fills   = _grab(r"Scalar fills \(per-instance\)\s*:\s*([\d.eE+]+)", sec)
                updates = _grab(r"Scalar updates \(per-instance\)\s*:\s*([\d.eE+]+)", sec)
                writes  = (fills or 0.0) + (updates or 0.0)
                rows.append(dict(layer=layer, level=level, dataspace=ds,
                                 reads=reads, writes=writes,
                                 energy_pJ=_grab(r"Energy \(total\)\s*:\s*([\d.eE+]+)\s*pJ", sec)))
        else:
            e = _grab(r"Energy \(total\)\s*:\s*([\d.eE+]+)\s*pJ", body)
            if e is not None:
                rows.append(dict(layer=layer, level=level, dataspace="Compute",
                                 reads=None, writes=None, energy_pJ=e))
    return rows


def classify(level):
    l = level.lower()
    if "dram" in l:                                return "DRAM"
    if "glb" in l or "buffer" in l or "sram" in l: return "Global buffer"
    if "mac" in l or "compute" in l:               return "Compute"
    return "Local (spads/RF/NoC)"


# ---- category layout --------------------------------------------------------
if SeperateBreakdown:
    PHYS_CATS = ["DRAM",
                 "Global buffer (read)", "Global buffer (write)",
                 "Local (read)", "Local (write)", "Compute"]
    ONCHIP_CATS = ["Global buffer (read)", "Global buffer (write)",
                   "Local (read)", "Local (write)"]
else:
    PHYS_CATS = ["DRAM", "Global buffer", "Local (spads/RF/NoC)", "Compute"]
    ONCHIP_CATS = ["Global buffer", "Local (spads/RF/NoC)"]

plot_cats  = PHYS_CATS + ["ECC decode", "Reconstruction"]
SPLIT_CATS = ("Global buffer", "Local (spads/RF/NoC)")


def category_energy(df):
    df = df.copy()
    df["reads"]  = df["reads"].fillna(0.0)
    df["writes"] = df["writes"].fillna(0.0)
    out = {c: 0.0 for c in plot_cats}
    for row in df.itertuples(index=False):
        cat, e = row.category, row.energy_pJ
        if SeperateBreakdown and cat in SPLIT_CATS:
            tot = row.reads + row.writes
            frac_r = (row.reads / tot) if tot > 0 else 1.0
            e_r, e_w = e * frac_r, e - e * frac_r
            if cat == "Global buffer":
                out["Global buffer (read)"]  += e_r
                out["Global buffer (write)"] += e_w
            else:
                out["Local (read)"]  += e_r
                out["Local (write)"] += e_w
        else:
            out[cat] = out.get(cat, 0.0) + e
    return pd.Series(out).reindex(plot_cats, fill_value=0.0)


def gather_model(arch, arch_yaml, out_root, model):
    rows, n_ok, n_skip = [], 0, 0
    n = len(model_layers[model])
    for i, L in enumerate(model_layers[model]):
        sig = (int(L["C"]), int(L["M"]), int(L["R"]), int(L["S"]),
               int(L["P"]), int(L["Q"]), int(L["Wstride"]), int(L["Hstride"]))
        stats = run_shape(arch, arch_yaml, out_root, sig)
        if stats is None:
            n_skip += 1
            continue
        rows += parse_stats(stats, f"{model}_{i}")
        n_ok += 1
    print(f"  {model:16s} {n_ok}/{n} layers ok, {n_skip} skipped", flush=True)
    if not rows:
        return None
    df = pd.DataFrame(rows)
    df = df[df.energy_pJ.notna() & (df.energy_pJ > 0)].reset_index(drop=True)
    df["category"] = df.level.map(classify)
    base   = category_energy(df)                             # all dataspaces
    base_w = category_energy(df[df.dataspace == "Weights"])  # WEIGHTS-only
    wt = df[df.dataspace == "Weights"].groupby("category").energy_pJ.sum()
    E_DRAM_W = float(wt.get("DRAM", 0.0))
    DRAM_W_READS = float(df[(df.category == "DRAM") &
                            (df.dataspace == "Weights")].reads.sum())
    return dict(base=base, base_w=base_w, E_DRAM_W=E_DRAM_W,
                DRAM_W_READS=DRAM_W_READS, ok=n_ok, skip=n_skip)


# ---------------- apply the three fixed-geometry ECC schemes -----------------
def build_stacks(raw):
    """All three arms share one BCH(BCH_N, BCH_K) codeword."""
    base, base_w = raw["base"], raw["base_w"]
    E_DRAM_W, DRAM_W_READS = raw["E_DRAM_W"], raw["DRAM_W_READS"]

    wpc  = BCH_K / WEIGHT_BITS          # weights carried by one codeword
    n_cw = DRAM_W_READS / wpc           # codewords, charged per weight read from DRAM

    parity_frac = BCH_N / BCH_K - 1.0   # baseline DRAM weight-traffic inflation
    sram_scale  = BCH_K / BCH_N         # Recon+ on-chip WEIGHT fraction

    # ---- 1. baseline: parity stored next to the data in DRAM ---------------
    baseline = base.copy()
    baseline["DRAM"] += E_DRAM_W * parity_frac
    if BASELINE_INFLATES_ONCHIP:
        for c in ONCHIP_CATS:
            baseline[c] = (base[c] - base_w[c]) + base_w[c] * (BCH_N / BCH_K)
    baseline["ECC decode"] = (n_cw * E_DECODE_BASE_PJ) if INCLUDE_ECC_DECODE else 0.0

    # ---- 2. embedded: parity inside the already-stored word ----------------
    embedded = base.copy()
    embedded["ECC decode"] = (n_cw * E_DECODE_EMB_PJ) if INCLUDE_ECC_DECODE else 0.0

    # ---- 3. Recon+: parity regenerated on-chip -----------------------------
    recon = base.copy()
    for c in ONCHIP_CATS:
        # scale ONLY the weight portion of on-chip energy by K/N; I/O untouched.
        recon[c] = (base[c] - base_w[c]) + base_w[c] * sram_scale
    recon["ECC decode"]     = ((n_cw * E_DECODE_EMB_PJ)
                               if (INCLUDE_ECC_DECODE and RECON_CHARGES_DECODE) else 0.0)
    recon["Reconstruction"] = n_cw * E_RECON_CW_PJ

    return pd.DataFrame({"baseline_hamming": baseline,
                         "embedded_ecc":     embedded,
                         "recon_plus":       recon})


# ---------------- palette / labels -------------------------------------------
palette = {
    "DRAM":                    "#2E5A87",
    "Global buffer":           "#4E9F3D",
    "Global buffer (read)":    "#6FBF5A",
    "Global buffer (write)":   "#2E5F24",
    "Local (spads/RF/NoC)":    "#E1A730",
    "Local (read)":            "#F0C05A",
    "Local (write)":           "#A9781A",
    "Compute":                 "#B03A2E",
    "ECC decode":              "#7D3C98",
    "Reconstruction":          "#1F9E8F",
}
if CVD_SAFE_PALETTE:   # Okabe-Ito; passes the colourblind-safety validator
    palette.update({
        "DRAM":                 "#0072B2",
        "Global buffer":        "#009E73",
        "Local (spads/RF/NoC)": "#E69F00",
        "Compute":              "#D55E00",
        "Reconstruction":       "#CC79A7",
    })

nice_label = {
    "Local (spads/RF/NoC)": "On-chip SRAM/RF",
    "Local (read)":         "On-chip SRAM/RF (read)",
    "Local (write)":        "On-chip SRAM/RF (write)",
}
# (dataframe column, bar tag drawn under the bar, CSV column prefix)
COLS = [("baseline_hamming", "Base.",  "base"),
        ("embedded_ecc",     "Embe.",  "embe"),
        ("recon_plus",       "Recon+", "recon")]

mpl.rcParams.update({
    "font.family": "DejaVu Sans", "axes.linewidth": 2.0,
    "axes.edgecolor": "#2b2b2b", "pdf.fonttype": 42, "ps.fonttype": 42,
})


# ---------------- shared grouped-stacked-bar renderer -------------------------
def _plot_grouped_stacks(groups, stacks, title, stem, group_fontsize=20):
    """One bar-group per entry in `groups`; three stacked bars per group.

    `groups` is a list of keys and `stacks` maps key -> the 3-column DataFrame.
    Used for BOTH figures: groups=models (one architecture) and
    groups=architectures (one model).
    """
    n = len(groups)
    maxtot_pJ = max(stacks[g][col].sum() for g in groups for col, _t, _p in COLS)
    div, unit = (1e9, "mJ") if maxtot_pJ / 1e6 >= 1000 else (1e6, "\u00b5J")

    active = [c for c in plot_cats
              if sum(stacks[g].loc[c].sum() for g in groups) > 1e-9]

    w, gap  = 0.34, 0.06
    centers = np.arange(n) * 2.40
    xoff    = {"baseline_hamming": -(w + gap), "embedded_ecc": 0.0, "recon_plus": (w + gap)}

    fig, ax = plt.subplots(figsize=(4.4 * n + 4, 10))
    bottoms = {col: np.zeros(n) for col, _t, _p in COLS}
    for cat in active:
        for col, _t, _p in COLS:
            v = np.array([stacks[g].loc[cat, col] for g in groups]) / div
            ax.bar(centers + xoff[col], v, w, bottom=bottoms[col], color=palette[cat],
                   edgecolor="white", linewidth=1.0, zorder=3,
                   label=nice_label.get(cat, cat) if col == "baseline_hamming" else None)
            bottoms[col] += v

    ymax = max(bottoms[col].max() for col, _t, _p in COLS)
    # adapt precision to magnitude: in mJ the totals are ~16 and "%.0f" would
    # collapse 15.9 and 15.3 to the same "16".
    dec = 0 if ymax >= 100 else (1 if ymax >= 10 else 2)

    for i, g in enumerate(groups):
        tb = bottoms["baseline_hamming"][i]
        for col, _t, _p in COLS:
            tot = bottoms[col][i]
            ax.text(centers[i] + xoff[col], tot + ymax * 0.006, f"{tot:.{dec}f}",
                    ha="center", va="bottom", fontsize=12, fontweight="bold", color="#2b2b2b")
        for col in ("embedded_ecc", "recon_plus"):
            sv = (tb - bottoms[col][i]) / tb * 100 if tb > 0 else 0.0
            ax.text(centers[i] + xoff[col], bottoms[col][i] + ymax * 0.045,
                    f"\u2212{sv:.1f}%", ha="center", va="bottom",
                    fontsize=13, fontweight="bold", color="#B03A2E")

    ax.set_xticks([])
    for i, g in enumerate(groups):
        for col, tag, _p in COLS:
            ax.text(centers[i] + xoff[col], -ymax * 0.015, tag, ha="center", va="top",
                    rotation=90, fontsize=15, color="#555", clip_on=False)
        ax.text(centers[i], -ymax * 0.27, g, ha="center", va="top",
                fontsize=group_fontsize, fontweight="medium", color="#111", clip_on=False)

    ncol = min(len(active), 4)
    legend_rows = math.ceil(len(active) / ncol)
    ax.set_ylabel(f"Inference energy ({unit})", fontsize=28, labelpad=12)
    ax.set_ylim(0, ymax * 1.22)
    ax.set_xlim(centers[0] - 1.4, centers[-1] + 1.4)
    ax.tick_params(axis="y", labelsize=20, width=2.0, length=9)
    ax.grid(axis="y", ls=":", alpha=0.35, zorder=0)
    ax.spines["top"].set_visible(False); ax.spines["right"].set_visible(False)
    ax.legend(loc="upper center", frameon=False, fontsize=17, ncol=ncol,
              bbox_to_anchor=(0.5, 1.03 + 0.055 * legend_rows),
              handlelength=1.2, columnspacing=1.5, labelspacing=0.4)
    ax.set_title(title, fontsize=22, pad=34 + 30 * legend_rows, fontweight="medium")

    fig.subplots_adjust(bottom=0.30, top=0.83, left=0.07, right=0.99)
    png = FIG_DIR / f"{stem}.png"
    pdf = FIG_DIR / f"{stem}.pdf"
    plt.savefig(png, dpi=400, bbox_inches="tight")
    plt.savefig(pdf, bbox_inches="tight")
    plt.close()

    rows = {}
    for g in groups:
        st = stacks[g]; row = {}
        for c in plot_cats:
            for col, _tag, pfx in COLS:
                row[f"{pfx}_{c}"] = st.loc[c, col] / 1e6
        tb = st["baseline_hamming"].sum()
        for col, _tag, pfx in COLS:
            tt = st[col].sum()
            row[f"{pfx}_total_uJ"]   = tt / 1e6
            row[f"{pfx}_saving_pct"] = (tb - tt) / tb * 100 if tb > 0 else 0.0
        rows[g] = row
    csv = FIG_DIR / f"{stem}_summary_uJ.csv"
    pd.DataFrame(rows).T.to_csv(csv)
    return png, pdf, csv


# ---------------- ALL architectures, one model, in a SINGLE figure ------------
def plot_all_archs(model, stacks_by_arch):
    """Bar-group per ARCHITECTURE, for one model. This is the single combined graph."""
    groups = [a for a in ARCHS if a in stacks_by_arch]
    if len(groups) < 2:
        print(f"  [skip] combined figure for {model}: needs >= 2 architectures")
        return None
    stacks = {a: stacks_by_arch[a][model] for a in groups}
    suffix = "_rw_split" if SeperateBreakdown else ""
    return _plot_grouped_stacks(
        groups, stacks,
        title=(f"{model}  \u00b7  45nm  \u00b7  8-bit weights  \u00b7  "
               f"BCH({BCH_N},{BCH_K}) t=2  \u00b7  all architectures"),
        stem=f"multiarch_bch63_k{BCH_K}_ALL_ARCHS_{model}{suffix}",
        group_fontsize=17)


# ---------------- one figure per architecture --------------------------------
def plot_arch(arch, stacks):
    """Bar-group per MODEL, for one architecture."""
    suffix = "_rw_split" if SeperateBreakdown else ""
    return _plot_grouped_stacks(
        list(stacks.keys()), stacks,
        title=(f"{arch}  \u00b7  45nm  \u00b7  8-bit weights  \u00b7  "
               f"BCH({BCH_N},{BCH_K}) t=2  \u00b7  Baseline vs Embedded vs Recon+"),
        stem=f"multiarch_bch63_k{BCH_K}_{arch}{suffix}")


# ================================ RUN =========================================
RAW_JSON = FIG_DIR / f"multiarch_bch63_k{BCH_K}_raw.json"


def raw_to_jsonable(raw):
    return {"base":   {k: float(v) for k, v in raw["base"].items()},
            "base_w": {k: float(v) for k, v in raw["base_w"].items()},
            "E_DRAM_W": float(raw["E_DRAM_W"]),
            "DRAM_W_READS": float(raw["DRAM_W_READS"]),
            "ok": int(raw["ok"]), "skip": int(raw["skip"])}


def raw_from_jsonable(d):
    return {"base":   pd.Series(d["base"]).reindex(plot_cats, fill_value=0.0),
            "base_w": pd.Series(d["base_w"]).reindex(plot_cats, fill_value=0.0),
            "E_DRAM_W": d["E_DRAM_W"], "DRAM_W_READS": d["DRAM_W_READS"],
            "ok": d["ok"], "skip": d["skip"]}


print("=" * 78)
print(f"BCH({BCH_N},{BCH_K}) SWEEP  --  Baseline / Embedded / Recon+  "
      f"across {len(ARCHS)} architectures")
print("=" * 78)
print(f"  quantization          : {WEIGHT_BITS}-bit weights")
print(f"  code                  : BCH({BCH_N},{BCH_K})  t=2  d_min=5  r={BCH_N-BCH_K}")
print(f"  weights per codeword  : {BCH_K/WEIGHT_BITS:.4f}  (all three arms)")
print(f"  DRAM weight inflation : baseline x{BCH_N/BCH_K:.4f} "
      f"(+{(BCH_N/BCH_K-1)*100:.1f}%), embedded/Recon+ x1.0")
print(f"  Recon+ on-chip scale  : {BCH_K/BCH_N:.4f} (weights only)")
if INCLUDE_ECC_DECODE:
    print(f"  decode  base / emb    : {E_DECODE_BASE_PJ} / {E_DECODE_EMB_PJ} pJ/cw  [ESTIMATE]")
else:
    print( "  decode                : 0 pJ for ALL THREE arms "
           "(INCLUDE_ECC_DECODE=False; category hidden from the legend)")
print(f"  reconstruction        : {E_RECON_CW_PJ:.7f} pJ per codeword")
print(f"  recon provenance      : {RECON_PROVENANCE}")
print(f"  palette               : {'Okabe-Ito (CVD-safe)' if CVD_SAFE_PALETTE else 'house'}")
print(f"  architectures         : {', '.join(ARCHS)}")
print(f"  output directory      : {FIG_DIR}")
print("=" * 78)

all_raw = {}
if RAW_JSON.exists():
    try:
        all_raw = {a: {m: raw_from_jsonable(r) for m, r in ms.items()}
                   for a, ms in json.loads(RAW_JSON.read_text()).items()}
        print(f"  loaded cached raw energies for: {', '.join(all_raw)}")
    except Exception as exc:
        print(f"  [warn] could not read {RAW_JSON.name}: {exc}")

if REPLOT_ONLY and not all_raw:
    raise SystemExit(f"REPLOT_ONLY is set but {RAW_JSON.name} has no data yet.")

summary = {}      # (arch, model) -> (emb saving %, recon saving %)
all_stacks = {}   # arch -> {model: stacks DataFrame}, for the combined figure

for arch in ARCHS:
    print(f"\n########## architecture: {arch} ##########", flush=True)

    if REPLOT_ONLY:
        # honour MODELS_TO_RUN on replot too, so scope is the same in both modes
        raws = {m: r for m, r in all_raw.get(arch, {}).items() if m in MODELS_TO_RUN}
        if not raws:
            print(f"  [skip] no cached raw energies for {arch} "
                  f"matching MODELS_TO_RUN")
            continue
        print(f"  replotting from {RAW_JSON.name} ({len(raws)} models)")
    else:
        arch_yaml = patched_arch_path(arch)
        out_root  = WORK / "outputs" / arch / "multimodel"
        out_root.mkdir(parents=True, exist_ok=True)
        raws = {}
        for model in MODELS_TO_RUN:
            if model not in model_layers:
                print(f"  [skip] {model}: not in model_layers.json")
                continue
            r = gather_model(arch, arch_yaml, out_root, model)
            if r is None:
                print(f"  !! {model}: no valid layers, skipped")
                continue
            raws[model] = r
        if not raws:
            print(f"  !! {arch}: no models produced results; skipping figure")
            continue
        # persist as soon as this architecture is done -- the run is long
        all_raw[arch] = raws
        RAW_JSON.write_text(json.dumps(
            {a: {m: raw_to_jsonable(r) for m, r in ms.items()}
             for a, ms in all_raw.items()}, indent=1))
        print(f"  raw energies saved to {RAW_JSON.name}")

    stacks = {m: build_stacks(raws[m]) for m in raws}
    all_stacks[arch] = stacks

    print(f"\n  --- {arch}: energy vs baseline ---")
    print(f"  {'model':16s} {'base uJ':>10s} {'emb uJ':>10s} {'recon+ uJ':>10s} "
          f"{'emb %':>8s} {'recon+ %':>9s}")
    for m in stacks:
        st = stacks[m]
        tb = st["baseline_hamming"].sum()
        te = st["embedded_ecc"].sum()
        tp = st["recon_plus"].sum()
        print(f"  {m:16s} {tb/1e6:10.2f} {te/1e6:10.2f} {tp/1e6:10.2f} "
              f"{(tb-te)/tb*100:7.1f}% {(tb-tp)/tb*100:8.1f}%")
        summary[(arch, m)] = ((tb - te) / tb * 100, (tb - tp) / tb * 100)

    png, pdf, csv = plot_arch(arch, stacks)
    print(f"\n  saved {png.name}\n  saved {pdf.name}\n  saved {csv.name}")

    m0 = list(stacks.keys())[0]
    st = stacks[m0]
    rec_share = st.loc["Reconstruction", "recon_plus"] / st["recon_plus"].sum() * 100
    print(f"  [{arch}] reconstruction is {rec_share:.2f}% of the Recon+ total on {m0}")


# ---------------- cross-architecture summary figure --------------------------
def plot_arch_comparison(summary):
    archs = [a for a in ARCHS if any(k[0] == a for k in summary)]
    if len(archs) < 2:
        print("\n[skip] architecture-comparison figure needs >= 2 architectures")
        return None
    models = [m for m in MODELS_TO_RUN if (archs[0], m) in summary]

    emb = np.array([[summary[(a, m)][0] for m in models] for a in archs])
    rec = np.array([[summary[(a, m)][1] for m in models] for a in archs])

    # Okabe-Ito blue / vermillion: a validated, colourblind-safe two-series pair
    C_EMB, C_REC = "#0072B2", "#D55E00"
    x = np.arange(len(archs)); w = 0.34

    ytop = max(emb.max(), rec.max())          # highest whisker cap
    fig, ax = plt.subplots(figsize=(3.0 * len(archs) + 5, 8))
    for off, vals, col, lab in ((-w/2 - 0.02, emb, C_EMB, "Embedded"),
                                (+w/2 + 0.02, rec, C_REC, "Recon+")):
        mean = vals.mean(axis=1)
        lo, hi = mean - vals.min(axis=1), vals.max(axis=1) - mean
        ax.bar(x + off, mean, w, color=col, edgecolor="white", linewidth=2.0,
               zorder=3, label=f"{lab} (mean of {len(models)} models)")
        ax.errorbar(x + off, mean, yerr=[lo, hi], fmt="none", ecolor="#2b2b2b",
                    elinewidth=2.0, capsize=7, capthick=2.0, zorder=4)
        # label ABOVE the upper whisker cap, not on top of it
        for xi, mv, hv in zip(x + off, mean, hi):
            ax.text(xi, mv + hv + ytop * 0.025, f"{mv:.1f}%", ha="center", va="bottom",
                    fontsize=15, fontweight="bold", color="#2b2b2b", zorder=5)

    ax.set_xticks(x)
    ax.set_xticklabels(archs, fontsize=17)
    ax.set_ylabel("Inference energy saved vs baseline (%)", fontsize=22, labelpad=12)
    ax.set_title(f"BCH({BCH_N},{BCH_K}) t=2  \u00b7  45nm  \u00b7  8-bit weights  \u00b7  "
                 f"energy saving by architecture\n"
                 f"bars = mean across {len(models)} CNNs, whiskers = min/max",
                 fontsize=21, pad=62, fontweight="medium")
    ax.tick_params(axis="y", labelsize=17, width=2.0, length=9)
    ax.grid(axis="y", ls=":", alpha=0.35, zorder=0)
    ax.spines["top"].set_visible(False); ax.spines["right"].set_visible(False)
    # legend above the axes: cannot collide with a bar or a whisker at any width
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, 1.075), ncol=2,
              frameon=False, fontsize=17, handlelength=1.4, columnspacing=2.0)
    ax.set_ylim(0, ytop * 1.22)
    fig.subplots_adjust(bottom=0.14, top=0.80, left=0.09, right=0.99)

    stem = f"multiarch_bch63_k{BCH_K}_architecture_comparison"
    png = FIG_DIR / f"{stem}.png"
    plt.savefig(png, dpi=400, bbox_inches="tight")
    plt.savefig(FIG_DIR / f"{stem}.pdf", bbox_inches="tight")
    plt.close()

    rows = {a: {"embedded_mean_pct": emb[i].mean(), "embedded_min_pct": emb[i].min(),
                "embedded_max_pct": emb[i].max(), "recon_mean_pct": rec[i].mean(),
                "recon_min_pct": rec[i].min(), "recon_max_pct": rec[i].max()}
            for i, a in enumerate(archs)}
    pd.DataFrame(rows).T.to_csv(FIG_DIR / f"{stem}.csv")
    return png


# ---- the single combined graph: every architecture side by side, per model ---
models_done = sorted({m for ms in all_stacks.values() for m in ms},
                     key=lambda m: MODELS_TO_RUN.index(m) if m in MODELS_TO_RUN else 99)
for m in models_done:
    have = {a: st for a, st in all_stacks.items() if m in st}
    if len(have) < 2:
        continue
    out = plot_all_archs(m, have)
    if out:
        print(f"\nsaved {out[0].name}  (+ .pdf, .csv)   <-- ALL ARCHITECTURES, {m}")

cmp_png = plot_arch_comparison(summary)
if cmp_png is not None:
    print(f"\nsaved {cmp_png.name}  (+ .pdf, .csv)")

print("\n" + "=" * 78)
print("Done. Files written to:", FIG_DIR)
print(f"Raw per-architecture energies cached in {RAW_JSON.name} -- set")
print("REPLOT_ONLY = True to rebuild every figure without running the mapper.")
if not INCLUDE_ECC_DECODE:
    print("NOTE: ECC decode charged as ZERO for all three arms; category omitted")
    print("      from the stacks and the legend.")
print("=" * 78)
