"""The ECC approaches, applied on top of Timeloop's raw energies.

All three arms share ONE code geometry, BCH(N, K) over `weight_bits`-bit
weights. They differ only in where the parity lives:

baseline  (the CONVENTIONAL-ECC baseline of Task 1)
    Parity is stored next to the data in DRAM. The inflation is NOT the flat
    `N/K` the pre-Task-1 model used: `parity.py` counts whole weights per
    codeword, the message bits no whole weight could use, the padding in the
    final codeword, and the whole 64-bit DRAM words the parity is actually read
    in. At BCH(63,51) over 8-bit weights that is 31.25% rather than 23.53% --
    the difference is real, and it is the difference between a number that
    reconciles by hand and one that does not.

    External parity is consumed by the off-chip ECC correction and never enters
    the on-chip weight SRAM/RF, so the baseline does not touch on-chip energy.
    `ECC_BASELINE_INFLATES_ONCHIP=1` reproduces the older behaviour and is NOT
    the conventional baseline.

embedded  (Task 2, `embedded.py`)
    Parity is embedded in the stored weights themselves: the MSB-first weight
    bit stream is cut into n-bit codewords and the n-k lowest-significance
    positions are overwritten with parity, which is what the embedding
    pipeline (ECC-CODE-Engine / Input_Embedding) actually does. Storage is
    weight_bits per weight with NO external parity, and the complete codeword
    is read for correction, so DRAM weight traffic is exactly Timeloop's --
    not K/N of it. Relative to the baseline only the external-parity term is
    removed; `embedded_dram()` reports the layout, the stored bits, the
    physical reads and the hand check. This is the reference point for "what
    does ECC cost if you do not pay for it in DRAM".

recon (Recon+)
    DRAM behaves as in `embedded`, and only K/N of the WEIGHT data is held on
    chip; the parity portion is regenerated by a synthesized reconstruction
    datapath, charged per codeword from a Design Compiler run. Inputs and
    outputs are untouched -- they carry no strong ECC.

Codewords are counted from DRAM weight reads: one codeword message carries
K/weight_bits weights, so n_codewords = dram_w_reads / (K/weight_bits).

An optional weak-ECC overlay (ECC_WEAK=1) models a light SRAM-side code
BCH(WEAK_N, WEAK_K) that inflates on-chip traffic by WEAK_N/WEAK_K: weights pay
it under every arm, inputs pay it under the baseline only.
"""
from __future__ import annotations

import json
import pathlib

import pandas as pd

from ..physics import baseline_dram, embedded, parity, widths
# The DC reconstruction table moved to physics/ in ProjectRestructure
# phase 4, so `arch/` can price an ERT bump without importing a driver.
# Imported here because every caller of these two says `stacks.` today.
from ..physics.recon_dc import load_recon_energy, load_recon_terms
from .. import config
from .energy import onchip_cats, plot_cats
from ..paths import ROOT

#: prompt_6 RULE 3 (4.3.3): the Design Compiler tables live in env.sh section 6
#: (`ECC_RECON_INCREMENTAL_PJ` / `ECC_RECON_IDLE_PJ`, flattened by section 10
#: into `cfg.recon_incremental_table` / `cfg.recon_idle_table`), not here, and
#: the lookup that reads them is `physics/recon_dc.py`.


# -------------------------------------------------------------- the three arms
def external_parity(cfg, raw, code_k=None, layer_weights=None, dram_word_bits=64):
    """The conventional-ECC baseline's DRAM parity cost, fully accounted.

    Returns `(energy_pJ, detail)`. `detail` is what goes into the result JSON:
    the code geometry, the stored payload/parity/padding, the traffic that
    crosses the DRAM boundary, the per-access energy it was billed at, and the
    hand-check that the accounting reconciles.

    `layer_weights` lets codewords be grouped per layer (the default and the
    conservative choice -- layers are separate tensors at separate addresses).
    Falling back to the model total is what `ECC_PARITY_GROUPING=model` does.
    """
    k = code_k or cfg.code_k
    geom = parity.CodeGeometry(cfg.code_n, k, cfg.weight_bits).validate()

    if layer_weights is None:
        layer_weights = [lp.get("weights", 0) for lp in (raw.per_layer or [])
                         if lp.get("status") == "ok"]
    if not layer_weights:
        layer_weights = [raw.weights]

    stored = parity.account_layers(layer_weights, geom, dram_word_bits,
                                   grouping=cfg.parity_grouping)
    traffic = parity.traffic_account(raw.dram_w_reads, stored, geom, dram_word_bits,
                                     charge_padding=cfg.parity_charge_padding)
    energy, per_scalar = parity.parity_energy_pj(traffic, raw.e_dram_w,
                                                 raw.dram_w_reads)
    ok, check = parity.hand_check(geom, sum(layer_weights), dram_word_bits)

    detail = {
        "code": geom.to_dict(),
        "grouping": cfg.parity_grouping,
        "charge_message_padding": cfg.parity_charge_padding,
        "dram_word_bits": dram_word_bits,
        "stored": stored.to_dict(),
        "traffic": traffic,
        "energy_pJ": energy,
        "pJ_per_dram_weight_scalar": per_scalar,
        "hand_check": check,
        "hand_check_passed": ok,
        "comparison_to_flat_model": {
            "flat_n_over_k_minus_1": geom.parity_overhead_ideal_frac,
            "accounted_overhead": traffic.get("overhead_vs_payload_frac", 0.0),
            "note": ("the flat model assumes the k-bit message field is fully "
                     "packed with weights; it is not, because a weight cannot "
                     "straddle a codeword"),
        },
    }
    return energy, detail


def embedded_dram(cfg, raw, code_k=None, layer_weights=None, dram_word_bits=64):
    """The embedded-ECC arm's DRAM weight accounting: complete codeword read,
    no external parity. Task 2.

    Returns `(external_energy_pJ, detail)` exactly like `external_parity()`, so
    a caller can write `raw.total + external` for either arm. The first value
    is 0.0 BY CONSTRUCTION -- the embedded representation stores nothing beside
    the weights -- and `detail` is what goes into the result JSON: the actual
    codeword layout and where it comes from, the stored payload/padding, the
    traffic that crosses the DRAM boundary (every bit of every weight read,
    message and parity alike), the physical-word estimate, the Timeloop DRAM
    weight energy that traffic was billed at, and the hand check.

    The layer grouping follows `ECC_PARITY_GROUPING`, the knob the baseline
    uses, so the two arms fall on the same per-tensor boundaries.
    """
    k = code_k or cfg.code_k
    layout = embedded.EmbeddedLayout(cfg.code_n, k, cfg.weight_bits).validate()

    if layer_weights is None:
        layer_weights = [lp.get("weights", 0) for lp in (raw.per_layer or [])
                         if lp.get("status") == "ok"]
    if not layer_weights:
        layer_weights = [raw.weights]

    stored = embedded.account_layers(layer_weights, layout, dram_word_bits,
                                     grouping=cfg.parity_grouping)
    traffic = embedded.traffic_account(raw.dram_w_reads, stored, layout, dram_word_bits)
    e_weights, e_external, per_scalar = embedded.dram_energy_pj(raw.e_dram_w,
                                                                 raw.dram_w_reads)
    ok, check = embedded.hand_check_layers(layout, layer_weights, dram_word_bits,
                                           grouping=cfg.parity_grouping)

    baseline_geom = parity.CodeGeometry(cfg.code_n, k, cfg.weight_bits).validate()
    detail = {
        "code": {"n": cfg.code_n, "k": k, "t": cfg.code_t,
                 "parity_bits_per_codeword": layout.parity_bits},
        "layout": layout.to_dict(),
        "layout_source": embedded.LAYOUT_SOURCE,
        "grouping": cfg.parity_grouping,
        "dram_word_bits": dram_word_bits,
        "stored": stored.to_dict(),
        "traffic": traffic,
        "dram_weight_energy_pJ": e_weights,
        "external_parity_energy_pJ": e_external,
        "energy_pJ": e_external,
        "pJ_per_dram_weight_scalar": per_scalar,
        "hand_check": check,
        "hand_check_passed": ok,
        "comparison_to_baseline_layout": {
            "baseline_weights_per_codeword": baseline_geom.weights_per_codeword,
            "baseline_stored_bits_per_weight": (
                baseline_geom.n / baseline_geom.message_used_bits * cfg.weight_bits),
            "embedded_weights_per_codeword": layout.weights_per_codeword,
            "embedded_stored_bits_per_weight": stored.bits_per_weight,
            "note": ("the baseline stores a codeword BESIDE the data and packs only "
                     "whole weights into its k-bit message field; the embedded "
                     "pipeline cuts the weight bit stream itself into n-bit codewords. "
                     "The two arms therefore count codewords differently, and neither "
                     "count is a modelling choice."),
        },
    }
    return e_external, detail


def mapper_narrowed_weight_energy(raw, cfg, q, cats):
    """prompt_6 RULE 1, the FOURTH narrowing site: per plotted category, the
    on-chip WEIGHT energy the mapper has ALREADY narrowed in this `Raw`.

    `build_stacks()`'s recon column scales on-chip weight energy by K/N on
    every evaluation. That is right for an 8-bit plan and doubles the saving
    on a q-bit one (an ERT arm's own record), so the level rows are read: a
    Weights row whose measured `Word bits` equals q was narrowed by the mapper
    and is left alone; one at `weight_bits` is the evaluator's; anything else
    stops. A row with no `word_bits` (a network row, or a record older than
    this field -- `energy.load_raw` re-gathers those) is the evaluator's, as
    before.
    """
    out = {}
    for lv in getattr(raw, "levels", None) or []:
        if lv.get("dataspace") != "Weights" or lv.get("category") not in cats:
            continue
        wb = lv.get("word_bits")
        if wb is None:
            continue
        wb = int(wb)
        if wb == cfg.weight_bits:
            continue
        if wb == q and q != cfg.weight_bits:
            out[lv["category"]] = out.get(lv["category"], 0.0) + float(lv.get("energy_pJ") or 0.0)
            continue
        raise ValueError(
            f"build_stacks: level {lv.get('level')!r} reports Word bits {wb}, which is "
            f"neither the weight width {cfg.weight_bits} nor q = {q} at "
            f"BCH({cfg.code_n},{cfg.code_k}); the arch and the code disagree and no "
            f"owner can be assigned to its narrowing (prompt_6 RULE 1)")
    return out


def build_stacks(cfg, raw, recon_pj, code_k=None, recon_pj_by_k=None,
                 parity_detail=None, recon_idle_pj=None, recon_engines=1):
    """Return a DataFrame: rows = plotted categories, columns = approaches.

    `code_k` overrides cfg.code_k for a K sweep; `recon_pj_by_k` supplies the
    matching per-codeword reconstruction energy. `parity_detail` receives the
    baseline's parity accounting when the caller wants to record it.

    prompt_6 RULE 3: `recon_pj` is the INCREMENTAL term (pJ per codeword
    event) and `recon_idle_pj` the idle term (pJ per cycle per engine; None =
    look it up for this K). The recon column charges

        Reconstruction = codewords x incremental + idle x cycles x engines

    with `cycles` from THIS `Raw` (its own plan; a record without cycles is
    refused, never charged zero) and `recon_engines` = 1: this arm counts
    its reconstructions from DRAM weight reads, i.e. it reconstructs at the
    chip ingress, where one engine sits. It is not one of the placement
    study's boundaries (CLAUDE.md).
    """
    k = code_k or cfg.code_k
    n = cfg.code_n
    if recon_pj_by_k is not None:
        recon_pj = recon_pj_by_k
    if recon_idle_pj is None:
        recon_idle_pj = load_recon_energy(cfg, k)[1]
    cycles = getattr(raw, "cycles", None)
    if "recon" in cfg.approaches and recon_idle_pj and not cycles:
        raise ValueError(
            f"build_stacks: the raw record carries no cycle count, and the "
            f"encoder's idle term is {recon_idle_pj:g} pJ per cycle per engine "
            f"(prompt_6 RULE 3). Refusing to charge it as zero -- re-gather the "
            f"record from the mapper cache (energy.load_raw does this when it is "
            f"not ECC_REPLOT_ONLY=1).")

    cats = plot_cats(cfg)
    onchip = onchip_cats(cfg)

    # ONE codeword geometry for the whole module, so the arm that counts
    # codewords and the arm that counts parity bits cannot disagree. Whole
    # weights only: `k / weight_bits` (6.375 at BCH(63,51)) is not a number of
    # weights, and using it made the codeword count 6% low.
    geom = parity.CodeGeometry(n, k, cfg.weight_bits).validate()
    weights_per_cw = geom.weights_per_codeword
    emb_weights_per_cw = cfg.emb_weights_per_cw_override or weights_per_cw
    sram_scale = k / n
    weak = cfg.weak_overhead

    base = raw.base.reindex(cats, fill_value=0.0)
    base_w = raw.base_w.reindex(cats, fill_value=0.0)
    base_i = raw.base_i.reindex(cats, fill_value=0.0)

    n_cw_base = raw.dram_w_reads / weights_per_cw
    n_cw_emb = raw.dram_w_reads / emb_weights_per_cw

    columns = {}

    # ---- 1. baseline: parity stored next to the data ------------------------
    if "baseline" in cfg.approaches:
        col = base.copy()
        # Accounted parity: whole weights per codeword, message padding, tail
        # padding and whole-DRAM-word granularity. See parity.py, and the
        # `comparison_to_flat_model` block in every result JSON for what the
        # old flat `n/k - 1` would have charged instead.
        e_parity, detail = external_parity(cfg, raw, code_k=k)
        # The baseline's DRAM cost is a per-bit PRICE (70 against 40) for an
        # array that also stores the parity, NOT extra traffic: the decoder is
        # on the DRAM die, so the parity is corrected there and never crosses
        # the datapath. `baseline_dram.charge_stack` folds the old traffic term
        # into DRAM instead when ECC_BASELINE_DRAM_PJ_PER_BIT is unset, which
        # reproduces the pre-2026-09-10 figures exactly.
        pricing = baseline_dram.charge_stack(cfg, raw, col, e_parity)
        if parity_detail is not None:
            parity_detail.update(detail)
            parity_detail["baseline_dram_pricing"] = pricing
        for c in onchip:
            # ECC_BASELINE_INFLATES_ONCHIP is NOT the conventional baseline:
            # external parity is consumed by the off-chip ECC correction and is
            # not written into on-chip weight storage. Kept to reproduce the
            # older figures, and off by default.
            portion = (base_w[c] * (1.0 + geom.parity_overhead_frac)
                       if cfg.baseline_inflates_onchip else base_w[c])
            # weak ECC: the baseline pays SRAM parity on weights AND on inputs
            col[c] = (base[c] - base_w[c]) + portion * weak + base_i[c] * (weak - 1.0)
        col["ECC decode"] = n_cw_base * cfg.decode_pj_base if cfg.decode_enabled else 0.0
        col["Reconstruction"] = 0.0
        columns["baseline"] = col

    # ---- 2. embedded: parity inside the already-stored word -----------------
    if "embedded" in cfg.approaches:
        col = base.copy()
        for c in onchip:
            # inputs are embedded too, so only weights pay the weak-ECC parity
            col[c] = (base[c] - base_w[c]) + base_w[c] * weak
        col["ECC decode"] = n_cw_emb * cfg.decode_pj_emb if cfg.decode_enabled else 0.0
        col["Reconstruction"] = 0.0
        columns["embedded"] = col

    # ---- 3. recon+: parity regenerated on chip ------------------------------
    if "recon" in cfg.approaches:
        col = base.copy()
        # RULE 1: weight energy the MAPPER already narrowed (a q-bit plan's
        # levels at Word bits == q) is not scaled again. On an 8-bit plan
        # `already` is 0 everywhere and this is the line it always was.
        q = widths.declared_datawidth(n, k, cfg.weight_bits)
        narrowed = mapper_narrowed_weight_energy(raw, cfg, q, onchip)
        for c in onchip:
            already = min(float(narrowed.get(c, 0.0)), float(base_w[c]))
            col[c] = ((base[c] - base_w[c]) + already * weak
                      + (base_w[c] - already) * sram_scale * weak)
        charges = cfg.decode_enabled and cfg.recon_charges_decode
        col["ECC decode"] = n_cw_emb * cfg.decode_pj_emb if charges else 0.0
        # prompt_7 Issue 4 -- CLOCK GATING, the same model the placement study
        # uses (recon.py evaluate_placement). g = 0 is algebraically identical
        # to the ungated `incremental x events + idle x engine_cycles`.
        # prompt_7, 2026-09-12: the recon arm stores DRAM exactly as the
        # embedded arm does, so it reconstructs on the EMBEDDED codeword count
        # (n/weight_bits = 7.875), not the baseline's whole-weight count
        # (k//weight_bits = 3). recon.py's placement study already counts this
        # way; using n_cw_base here made the sweep arm's incremental term
        # 2.625x too large and the two figure families disagree.
        _n_cw = n_cw_emb
        _idle = float(recon_idle_pj)
        _ec = float(cycles or 0) * recon_engines
        _g = max(0.0, min(1.0, float(getattr(cfg, "recon_clock_gating_pct", 0.0)) / 100.0))
        if _g:
            col["Reconstruction"] = (_n_cw * (recon_pj + _idle)
                                     + _idle * (1.0 - _g) * max(_ec - _n_cw, 0.0))
        else:
            col["Reconstruction"] = _n_cw * recon_pj + _idle * _ec
        columns["recon"] = col

    df = pd.DataFrame({a: columns[a] for a in cfg.approaches})
    return df.reindex(cats, fill_value=0.0)


def savings(stacks, approaches):
    """Percent energy saved versus the leftmost arm, per approach."""
    ref_name = approaches[0]
    ref = float(stacks[ref_name].sum())
    out = {}
    for a in approaches:
        total = float(stacks[a].sum())
        out[a] = ((ref - total) / ref * 100.0) if ref > 0 else 0.0
    return out


def recon_pj_for_k(cfg, k):
    """The INCREMENTAL term for the K sweep (prompt_6 RULE 3); the idle term
    is `load_recon_energy(cfg, k)[1]`. Same lookup as `load_recon_energy`."""
    return load_recon_energy(cfg, k)[0]


def k_label(cfg, k):
    """Tick label for a K sweep: the corrected bit-error rate the code tolerates."""
    from ..config import BCH63_KTOD
    d = BCH63_KTOD.get(k)
    if not d:
        return f"BCH({cfg.code_n}, {k})"
    t = (d - 1) // 2
    ber = round(t / cfg.code_n * 100 * 2) / 2  # nearest 0.5 %
    return f"{ber:g}% BER\nBCH({cfg.code_n}, {k}, {t})"
