"""Scrape the Design Compiler AREA reports into `archs/_shared/recon_area.yaml`.

RUN ONCE, WHEN NEW REPORTS ARRIVE -- the package reads the YAML, never the
`.rpt` files (the user's instruction, 2026-09-14). A synthesis report is a
measurement archive of tens of files; a per-run parse of it would put a
filesystem walk on the hot path of every figure and would silently report
nothing when the reports are not checked out. The YAML is the citable record.

    python3 tools/scrape_dc_area.py            # rewrite the YAML
    python3 tools/scrape_dc_area.py --check    # verify it still matches, exit 1 if not

WHAT IS SCRAPED, AND WHAT IS DELIBERATELY NOT.

`Total cell area:` from `<config>/active/area.rpt` -- the placed standard-cell
area of the whole `reconstruction_stage` design, in the library's own unit.

THE IDLE REPORT IS READ AND COMPARED, NEVER ADDED. `active/` and `idle/` are
the same netlist under two switching activities: the POWER differs and the AREA
cannot, and every one of the twelve configurations reports the two areas
byte-identical. So the scrape asserts that equality and records the active
number alone. Adding them would double the engine (the user's instruction,
2026-09-14).

`Net Interconnect area` is `undefined (No wire load specified)` in every report
and `Total area` is therefore `undefined` too. What is recorded is CELL area,
pre-layout, and the YAML says so rather than implying a die area.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys
import os

ROOT = pathlib.Path(__file__).resolve().parents[1]
SNAPSHOTS = ROOT / "data" / "dc" / "report_snapshots"
OUT = ROOT / "archs" / "_shared" / "recon_area.yaml"

#: `Total cell area:` -- the one number this file exists for.
_TOTAL = re.compile(r"^Total cell area:\s+([0-9.]+)\s*$", re.M)
#: The library the numbers are in, for the provenance line.
_LIB = re.compile(r"^\s+(\S+)\s+\(File:\s*(\S+)\)\s*$", re.M)
#: `BCH_63_39_t4` -> n=63, k=39, t=4. A configuration whose id does not parse
#: is recorded under its id with no (n, k) and can only be looked up by name.
_BCH = re.compile(r"^BCH_(\d+)_(\d+)_t(\d+)$")


def _total_cell_area(path):
    m = _TOTAL.search(path.read_text())
    if not m:
        raise SystemExit(f"{path}: no `Total cell area:` line")
    return float(m.group(1))


def _library(path):
    m = _LIB.search(path.read_text())
    return (m.group(1), m.group(2)) if m else (None, None)


def scrape():
    """[{configuration_id, n, k, t, area_um2, library, ...}], sorted by id."""
    if not SNAPSHOTS.is_dir():
        raise SystemExit(f"no DC reports under {SNAPSHOTS}")
    out, libs = [], set()
    for d in sorted(SNAPSHOTS.iterdir()):
        active, idle = d / "active" / "area.rpt", d / "idle" / "area.rpt"
        if not active.is_file():
            print(f"  [skip] {d.name}: no active/area.rpt")
            continue
        area = _total_cell_area(active)
        # THE ASSERTION THAT STOPS THE DOUBLE COUNT. Same netlist, two
        # switching activities: the area cannot differ, and if a future report
        # says it does, that is a synthesis difference nobody has explained and
        # this scrape must stop rather than pick one.
        if idle.is_file():
            idle_area = _total_cell_area(idle)
            if abs(idle_area - area) > 1e-9:
                raise SystemExit(
                    f"{d.name}: active area {area} != idle area {idle_area}. "
                    f"The two reports are the same netlist under two switching "
                    f"activities and their AREA cannot differ; refusing to "
                    f"choose one. Check the synthesis run.")
        lib, libfile = _library(active)
        libs.add((lib, libfile))
        row = {"configuration_id": d.name, "area_um2": area}
        m = _BCH.match(d.name)
        if m:
            row.update(n=int(m.group(1)), k=int(m.group(2)), t=int(m.group(3)))
        out.append(row)
    return out, sorted(libs)


HEADER = """\
# =====================================================================
#  recon_area.yaml -- THE SYNTHESIZED RECONSTRUCTION ENGINE'S AREA
#
#  GENERATED by `python3 tools/scrape_dc_area.py` from the Design
#  Compiler reports under `data/dc/report_snapshots/<config>/active/
#  area.rpt`.  Do not edit by hand: `--check` fails when this file and
#  the reports disagree, and `tests/test_recon_area.py` runs it.
#
#  WHAT THE NUMBER IS.  `Total cell area:` of the `reconstruction_stage`
#  design -- PRE-LAYOUT STANDARD-CELL area, in square microns, in the
#  library named below.  Every report says `Net Interconnect area:
#  undefined (No wire load specified)` and therefore `Total area:
#  undefined`, so this is CELL area and not a die area; a placed-and-
#  routed engine is larger by the fill and routing overhead this flow
#  does not model.
#
#  ACTIVE ONLY, ON PURPOSE.  `active/` and `idle/` are the same netlist
#  under two switching activities.  Their POWER differs -- which is what
#  `data/dc/BCH_N63_results.json` records as the two energy terms -- and
#  their AREA is identical in all twelve configurations.  Only the active
#  number is stored, and the scraper REFUSES if the two ever disagree:
#  adding them would count one engine twice.
#
#  ONE ENGINE.  This is the area of ONE reconstruction stage.  What
#  multiplies it is the placement -- how many engines a boundary
#  instantiates -- and that is `physics/granularity.py`'s count, not a
#  number in this file.
#
#  NON-MONOTONICITY, RECORDED NOT CORRECTED.  More correction capability
#  should cost more area, and across the BCH(63,K) family it does except
#  for one inversion: BCH(63,36) t=5 is 2353.54 um2 against BCH(63,30)
#  t=6's 2313.65, so the stronger code synthesized 1.7 % SMALLER.  That
#  is synthesis variance (different optimisation outcomes on two
#  independent runs of the same flow), not a corrected number: these are
#  the measurements as reported.
# =====================================================================
version: 1
"""


def render(rows, libs):
    lines = [HEADER]
    lib, libfile = libs[0] if libs else (None, None)
    if len(libs) > 1:
        raise SystemExit(f"reports use more than one library: {libs}")
    lines.append(f"library: {lib}")
    lines.append(f"library_file: {libfile}")
    lines.append("unit: um2")
    lines.append("measurement: total_cell_area_active_prelayout")
    lines.append("source: data/dc/report_snapshots/<configuration_id>/active/area.rpt")
    lines.append("")
    lines.append("# configuration_id -> the engine's area. `n`/`k`/`t` are parsed from")
    lines.append("# the id and are how `physics/recon_dc.py` matches a code to a row.")
    lines.append("engines:")
    for r in rows:
        lines.append(f"  {r['configuration_id']}:")
        lines.append(f"    area_um2: {r['area_um2']}")
        if "n" in r:
            lines.append(f"    n: {r['n']}")
            lines.append(f"    k: {r['k']}")
            lines.append(f"    t: {r['t']}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify the YAML matches the reports; write nothing")
    args = ap.parse_args()

    rows, libs = scrape()
    text = render(rows, libs)
    if args.check:
        if not OUT.exists():
            print(f"MISSING: {OUT}")
            return 1
        if OUT.read_text() != text:
            print(f"STALE: {OUT} does not match the reports under {SNAPSHOTS}")
            print("  -> python3 tools/scrape_dc_area.py")
            return 1
        print(f"ok  {OUT.relative_to(ROOT)} matches {len(rows)} report(s)")
        return 0
    # ATOMIC, with a pre-edit copy -- CLAUDE.md's rule for every write.
    tmp = OUT.with_suffix(".yaml.tmp")
    tmp.write_text(text)
    os.replace(tmp, OUT)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} configuration(s)")
    for r in rows:
        print(f"  {r['configuration_id']:<24} {r['area_um2']:>12.6f} um2")
    return 0


if __name__ == "__main__":
    sys.exit(main())
